### ISSUE TITLE
Can I predict GO term by expression data?

### ISSUE THREAD

**Issue by lijing28101** [kevinrue/GOexpress#3]
Hi, I'm interested in this package. 
I have a new gene annotation for a species, and I predict GO for genes by sequence and domain similarity. However, about half of the genes cannot match a GO term. I have gene expression data from multiple studies and conditions. Can I predict GO for those unknown genes with expression matrix and genes with known GO?

Thanks,
Jing

**Comment by kevinrue** [comment]
Unfortunately, GOexpress is not designed at all for predicting GO. It expects knows gene-GO associations to score and rank GO using gene expression.

I have never tried to predict GO myself, so I cannot redirect you to any other package. You would need to keep searching or write some code yourself, I'm afraid.

Good luck!
